---
# Required: Terraform, TFENV, Trivy, TFLINT, terraform-docs, tflint, 
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args:
          - -b
          - dev
          - -b
          - test
          - -b
          - stage
          - -b
          - perf
          - -b
          - prod
          - -b
          - nprd
          - -b
          - main
          - -b
          - master
      - id: pretty-format-json
  - repo: "https://github.com/gruntwork-io/pre-commit"
    rev: v0.1.23
    hooks:
      # - id: gofmt # context: https://github.com/gruntwork-io/pre-commit/issues/67
      - id: shellcheck
      - id: terraform-fmt
      - id: terraform-validate
        args:
          - --args=-no-color
      - id: terragrunt-hclfmt
      - id: tflint
      - id: yapf
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.1
    hooks:
      - id: terraform_docs
        args: 
        - --args=--output-file README.md
        - --args=--output-mode inject
      - id: terraform_trivy
        args:
            - --args=--severity HIGH,CRITICAL
            - --args=--ignorefile ./.trivyignore
            - --args=--skip-dirs="**/.terraform"
            - --args=--skip-dirs="*/modules"
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.485'  # Use latest version
    hooks:
      - id: checkov
        name: Checkov Terraform Compliance Scan
        args:
          - --directory=.
          - --framework=terraform
          - --external-checks-git=git@github.com:CiscoOpsStack/ops_stack_github_actions.git
          - --external-checks-dir=checkov-policies
          - --check=CKV_OPSTK_*,CKV2_OPSTK_*  # Only run custom policies

